export const TOGGLE_EMPLOYEE_PUNCH = 'TOGGLE_EMPLOYEE_PUNCH';

export const DISPATCH_WORK_ORDER = 'DISPATCH_WORK_ORDER';
export const ARRIVE_WORK_ORDER = 'ARRIVE_WORK_ORDER';
export const DEPART_WORK_ORDER = 'DEPART_WORK_ORDER';
export const RESOLVE_WORK_ORDER = 'RESOLVE_WORK_ORDER';
export const NOTE_TO_DB = 'NOTE_TO_DB';