export const TOGGLE_EMPLOYEE_PUNCH = 'TOGGLE_EMPLOYEE_PUNCH';

export const DISPATCH_WORK_ORDER = 'DISPATCH_WORK_ORDER';
export const ARRIVE_WORK_ORDER = 'ARRIVE_WORK_ORDER';
export const DEPART_WORK_ORDER = 'DEPART_WORK_ORDER';
export const RESOLVE_WORK_ORDER = 'RESOLVE_WORK_ORDER';
export const ADD_PART_TO_STATE = 'ADD_PART_TO_STATE';
export const SAVE_NOTE_TEXT = 'SAVE_NOTE_TEXT';